### ISSUE TITLE
Add possibility to install directly without Poetry

### ISSUE THREAD

**Issue by JrooTJunior** [bryanforbes/gino-stubs#1]
Publish please this stubs to PyPi or generate setup.py for adding posibility of installation you'r stubs via pip or Pipenv because now it's impossible.

**Comment by bryanforbes** [comment]
`pip` 19.2.3 and higher handles installing from the repo just fine. What version are you using?

I'm a bit hesitant to publish the stubs because of the way `Gino.Model` works and `mypy` not being able to handle it well.

**Comment by JrooTJunior** [comment]
I use Pipenv:
``` bash
$ pipenv --version
pipenv, version 2018.11.15.dev0
```
``` bash
$ pipenv run pip --version
pip 19.3.1 from <path> (python 3.7)
```

Pipenv can't install package from this repo
``` bash
pipenv install --dev git+https://github.com/bryanforbes/gino-stubs.git@master#egg=gino-stubs
pipenv install --dev git+git@github.com:bryanforbes/gino-stubs.git@master#egg=gino-stubs
pipenv install --dev https://github.com/bryanforbes/gino-stubs/archive/master.zip#egg=gino-stubs
```

And... With pip it can be installed. I re-check it.

**Comment by Pentusha** [comment]
``pipenv, version 2018.11.26``

``pipenv install --dev git+https://github.com/bryanforbes/gino-stubs.git@master#egg=gino-stubs`` 

works fine

**Comment by bryanforbes** [comment]
@Pentusha thanks for confirming!
